"""Build explicit synthetic frontend reference downloads using production writers."""

from datetime import date
from decimal import Decimal
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile

from reportlab.pdfgen.canvas import Canvas

from stmtconv.catalog import load_catalog
from stmtconv.core.models import Statement, StatementSummary, Transaction
from stmtconv.core.validate import validate
from stmtconv.export import csv_writer, excel, ofx


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    output = root / "frontend/public/samples"
    output.mkdir(parents=True, exist_ok=True)
    statement = validate(
        Statement(
            id="s0001",
            summary=StatementSummary(
                opening=Decimal("1000"),
                closing=Decimal("2987.50"),
                total_debits=Decimal("12.50"),
                total_credits=Decimal("2000"),
                period_start=date(2026, 1, 1),
                period_end=date(2026, 1, 31),
                account_mask="****1234",
                account_key="synthetic-frontend-account",
            ),
            transactions=[
                Transaction(
                    id="row-a",
                    date=date(2026, 1, 2),
                    description="Fake café, grocery",
                    debit=Decimal("12.50"),
                    balance=Decimal("987.50"),
                    source_file="synthetic-january.pdf",
                    page=1,
                    engine="text",
                    raw_text="fake",
                ),
                Transaction(
                    id="row-b",
                    date=date(2026, 1, 3),
                    description="Fake salary",
                    credit=Decimal("2000"),
                    balance=Decimal("2987.50"),
                    source_file="synthetic-january.pdf",
                    page=1,
                    engine="text",
                    raw_text="fake",
                ),
            ],
            pages=[1],
        ),
        Decimal("0.01"),
    )
    formats = load_catalog(root / "config").exports.formats
    excel.write(statement, output / "sample.xlsx", formats["excel"])
    for name, filename in {
        "csv": "sample.csv",
        "qb_csv3": "sample-qb3.csv",
        "qb_csv4": "sample-qb4.csv",
        "xero_csv": "sample-xero.csv",
    }.items():
        data = csv_writer.serialize(
            statement,
            formats[name],
            "%Y-%m-%d" if name == "csv" else "%m/%d/%Y",
            bom=name == "csv",
        )
        assert data == (root / f"tests/golden/{name}.csv").read_bytes()
        (output / filename).write_bytes(data)
    (output / "sample.ofx").write_bytes(ofx.serialize(statement, "20260131000000"))
    canvas = Canvas(str(output / "synthetic-january.pdf"), pagesize=(612, 792), invariant=1)
    canvas.setTitle("Synthetic January statement — not a real bank statement")
    text = canvas.beginText(45, 735)
    text.setFont("Helvetica", 11)
    for line in [
        "SAMPLE BANK - FICTIONAL STATEMENT ONLY",
        "January 2026 | Account ending 1234 | USD",
        "Opening balance: 1,000.00",
        "",
        "2026-01-02 | Fake café, grocery | Debit 12.50 | Balance 987.50",
        "2026-01-03 | Fake salary | Credit 2,000.00 | Balance 2,987.50",
        "",
        "Closing balance: 2,987.50",
        "Synthetic frontend source fixture. No client data.",
    ]:
        text.textLine(line)
    canvas.drawText(text)
    canvas.showPage()
    canvas.save()
    (output / "README.txt").write_text(
        "FIXED SYNTHETIC REFERENCE FILES\n"
        "Generated by the existing Python writers, not from selected files or UI edits.\n"
        "Two fictional January rows. OFX uses a synthetic identity and UNKNOWN bank ID.\n"
        "Actual accounting import acceptance must be tested separately.\n",
        encoding="utf-8",
    )
    with ZipFile(output / "sample-package.zip", "w", ZIP_DEFLATED) as package:
        for path in sorted(output.iterdir()):
            if path.suffix != ".zip":
                package.write(path, path.name)
    print("Synthetic source and six reference export formats generated; CSV goldens match.")


if __name__ == "__main__":
    main()
